_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 41
                - 48
                - 49
                - 55
            "2":
                - 1
                - 41
                - 48
                - 49
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
batch_size:
    value: 8
env_config:
    value:
        data_base_dir: ./data
        embedding_base_dir: ./embeddings
        json_data_list: ./temp_work_dir/datalist.json
        log_dir: ./logs
        model_dir: ./models
        model_filename: diff_unet_ckpt.pt
        output_dir: ./predictions
        output_prefix: unet_2d
        trained_autoencoder_path: ./runs/lima_20250917_1334/model_best.pt
        trained_unet_path: null
learning_rate:
    value: 0.0001
main:
    value:
        image_dir: /home/mhuber/Thesis/data/KermanyV3_micro/train
        latents_path: ./latents/lima
        trained_autoencoder_path: ./runs/lima_20250917_1334/model_best.pt
        trained_unet_path: null
model:
    value:
        autoencoder:
            attention_levels:
                - false
                - false
                - false
            dim_split: 1
            in_channels: 1
            latent_channels: 4
            norm_eps: 1e-06
            norm_float16: true
            norm_num_groups: 32
            num_channels:
                - 64
                - 128
                - 256
            num_res_blocks:
                - 2
                - 2
                - 2
            num_splits: 1
            out_channels: 1
            spatial_dims: 2
            use_checkpointing: false
            use_convtranspose: false
            with_decoder_nonlocal_attn: false
            with_encoder_nonlocal_attn: false
model_config:
    value:
        diffusion_unet_inference:
            bottom_region_index:
                - 0
                - 0
                - 1
                - 0
            dim:
                - 256
                - 256
                - 128
            num_inference_steps: 1000
            random_seed: 42
            spacing:
                - 1
                - 1
                - 1
            top_region_index:
                - 0
                - 1
                - 0
                - 0
        diffusion_unet_train:
            batch_size: 8
            cache_rate: 0
            lr: 0.0001
            n_epochs: 1000
        save_every: 1
num_epochs:
    value: 1000
num_timesteps:
    value: 1000
start_epoch:
    value: 0
vae_def:
    value:
        autoencoder_def:
            _target_: monai.apps.generation.maisi.networks.autoencoderkl_maisi.AutoencoderKlMaisi
            attention_levels:
                - false
                - false
                - false
            dim_split: 1
            in_channels: '@image_channels'
            latent_channels: '@latent_channels'
            norm_eps: 1e-06
            norm_float16: true
            norm_num_groups: 32
            num_channels:
                - 64
                - 128
                - 256
            num_res_blocks:
                - 2
                - 2
                - 2
            num_splits: 8
            out_channels: '@image_channels'
            spatial_dims: '@spatial_dims'
            use_checkpointing: false
            use_convtranspose: false
            with_decoder_nonlocal_attn: false
            with_encoder_nonlocal_attn: false
        controlnet_def:
            _target_: monai.apps.generation.maisi.networks.controlnet_maisi.ControlNetMaisi
            attention_levels:
                - false
                - false
                - true
                - true
            conditioning_embedding_in_channels: 8
            conditioning_embedding_num_channels:
                - 8
                - 32
                - 64
            in_channels: '@latent_channels'
            num_channels:
                - 64
                - 128
                - 256
                - 512
            num_head_channels:
                - 0
                - 0
                - 32
                - 32
            num_res_blocks: 2
            spatial_dims: '@spatial_dims'
            use_flash_attention: true
        diffusion_unet_def:
            _target_: monai.apps.generation.maisi.networks.diffusion_model_unet_maisi.DiffusionModelUNetMaisi
            attention_levels:
                - false
                - false
                - true
                - true
            in_channels: '@latent_channels'
            include_bottom_region_index_input: false
            include_spacing_input: false
            include_top_region_index_input: false
            num_channels:
                - 64
                - 128
                - 256
                - 512
            num_head_channels:
                - 0
                - 0
                - 32
                - 32
            num_res_blocks: 2
            out_channels: '@latent_channels'
            spatial_dims: '@spatial_dims'
            use_flash_attention: true
        image_channels: 1
        latent_channels: 4
        noise_scheduler:
            _target_: monai.networks.schedulers.ddpm.DDPMScheduler
            beta_end: 0.0195
            beta_start: 0.0015
            clip_sample: false
            num_train_timesteps: 1000
            schedule: scaled_linear_beta
        spatial_dims: 2
